{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otus-postgres.fullname" . }}-secrets
  labels:
    {{- include "otus-postgres.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secret.postgres_user }} 
  POSTGRES_PASSWORD: {{ .Values.secret.postgres_password }}
{{- end }}
