$script1 = <<-SCRIPT
echo start custom provizioning...
# Add Docker's official GPG key:
sudo apt-get update
sudo apt-get -y install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

# Install the Docker packages.
sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
SCRIPT


Vagrant.configure("2") do |config|

  config.vm.define "vmnode" do |node|
    node.vm.network "private_network", ip: "192.168.60.200"
    node.vm.hostname = "vnmode"
    node.vm.define "vmnode"
    node.vm.box_download_insecure = true
    node.vm.box = "generic/ubuntu2004"
    node.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 2
    end
    node.vm.provision "shell", inline: $script1
    #node.vm.provision "ansible", playbook: "test.yml"
  end

end
